### ISSUE TITLE
Node Action run completed with exit code 1

### ISSUE THREAD

**Issue by mssadewa** [pinkasey/cpanel-deploy-action#1]
Hello,

Thanks for your actions.
I've got some error with **task_id**

```
##[debug]startDeployRes: {
##[debug]  "data": null,
##[debug]  "errors": null,
##[debug]  "metadata": {},
##[debug]  "warnings": null,
##[debug]  "messages": null,
##[debug]  "status": 1
##[debug]}
failed deployment duration: 2809
##[debug]errorBody: undefined

::set-output name=duration::2809
##[debug]steps.deploy.outputs.duration='2809'
Error: Cannot read properties of null (reading 'task_id')
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Deploy to cPanel

````

Since it was connected to Cpanel uapi, I assume the root cause is not from my master.yml
Did you know what **task_id** actually mean?

**Comment by mssadewa** [comment]
So, basically my updated repo (github) has `.cpanel.yml` but my unupdated repo on cPanel has no `.cpanel.yml` that's why the uAPI return an blank **task_id**. 

And make sure `.cpanel.yml` contains command with **exit code 0** (if any) otherwise action will fail.

**Comment by pinkasey** [comment]
Thanks for the update 🙂
